### ISSUE TITLE
shifts extension

### ISSUE THREAD

**Issue by jofmi** [collectivo-dev/collectivo#37]
This issue is to track progress on the collectivo shifts extension

- [ ] Directus Database Structure
    - [ ] Shift user fields
    - [ ] Shift model
    - [ ] Shift repetition logic
    - [ ] Shift score logic
- [ ] Directus Admin App
    - [ ] Creating shifts 
    - [ ] See unfilled shifts
    - [ ] Confirm shift fulfilled
- [ ] Collectivo Frontend (Nuxt)
    - [ ] Choosing shift user type
    - [ ] Registering and unregistering from a shift

**Comment by Theophile-Madet** [comment]
WIP : #46
